from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from .db import write_csv


@dataclass(frozen=True)
class SignalWeights:
    record: float
    starter: float
    bullpen: float
    lineup: float

    @property
    def label(self) -> str:
        return f"record={self.record:.2f}|starter={self.starter:.2f}|bullpen={self.bullpen:.2f}|lineup={self.lineup:.2f}"


def backtest_record_signal_strategy(frame: pd.DataFrame, year: int, report_dir: Path) -> dict[str, pd.DataFrame]:
    """Backtest a simple pregame signal blend.

    Uses only columns generated by ``build_training_frame`` before each row's
    game state is updated, so records, starter stats, bullpen usage, and lineup
    ratings are all pregame values.
    """

    games = prepare_signal_frame(frame, year)
    if games.empty:
        raise RuntimeError(f"No completed games available for {year}.")

    weights = weight_grid()
    summary_rows = []
    by_bucket_rows = []
    scored_frames = []

    for weight in weights:
        scored = score_games(games, weight)
        metrics = summarize(scored, weight.label, weight)
        summary_rows.append(metrics)
        for bucket, group in scored.groupby("record_gap_bucket", dropna=False):
            by_bucket_rows.append(summarize(group, weight.label, weight, bucket=str(bucket)))
        scored_frames.append(scored.assign(weight_combo=weight.label))

    summary = pd.DataFrame(summary_rows).sort_values(
        ["accuracy", "bets"],
        ascending=[False, False],
    )
    by_bucket = pd.DataFrame(by_bucket_rows)
    all_scored = pd.concat(scored_frames, ignore_index=True)
    baselines = baseline_report(games)

    report_dir.mkdir(parents=True, exist_ok=True)
    write_csv(summary, report_dir / f"record_signal_backtest_{year}_summary.csv")
    write_csv(by_bucket, report_dir / f"record_signal_backtest_{year}_buckets.csv")
    write_csv(baselines, report_dir / f"record_signal_backtest_{year}_baselines.csv")
    best_label = str(summary.iloc[0]["weight_combo"])
    write_csv(
        all_scored[all_scored["weight_combo"].eq(best_label)],
        report_dir / f"record_signal_backtest_{year}_best_predictions.csv",
    )

    return {
        "summary": summary,
        "by_bucket": by_bucket,
        "baselines": baselines,
        "best_predictions": all_scored[all_scored["weight_combo"].eq(best_label)].reset_index(drop=True),
    }


def prepare_signal_frame(frame: pd.DataFrame, year: int) -> pd.DataFrame:
    df = frame[(frame["season"].eq(year)) & frame["target_home_win"].notna()].copy()
    if df.empty:
        return df
    df = attach_season_to_date_records(df)

    df["home_record_net"] = df["home_wins_prior"] - df["home_losses_prior"]
    df["away_record_net"] = df["away_wins_prior"] - df["away_losses_prior"]
    df["record_games_gap"] = ((df["home_record_net"] - df["away_record_net"]).abs() / 2.0).fillna(0.0)
    df["record_gap_bucket"] = df["record_games_gap"].map(record_gap_bucket)

    df["season_win_pct_diff"] = df["home_season_win_pct_prior"] - df["away_season_win_pct_prior"]
    df["record_advantage"] = signed_clip(df["season_win_pct_diff"], 0.12) * np.clip(df["record_games_gap"] / 10.0, 0.0, 1.5)
    df["starter_xfip_proxy_advantage"] = signed_clip(df["starter_fip_advantage"], 2.5)
    df["bullpen_availability_advantage"] = signed_clip(df["bullpen_fatigue_advantage"], 1.0)
    df["lineup_wrc_proxy_advantage"] = signed_clip(
        df["lineup_offense_advantage"].fillna(0.0) + df.get("lineup_platoon_advantage", 0.0),
        0.25,
    )

    df["actual_home_win"] = df["target_home_win"].astype(bool)
    df["actual_winner"] = np.where(df["actual_home_win"], df["home_team"], df["away_team"])
    return df


def attach_season_to_date_records(df: pd.DataFrame) -> pd.DataFrame:
    df = df.sort_values(["game_date", "game_pk"]).reset_index(drop=True)
    records: dict[int, list[int]] = {}
    out_rows = []
    for row in df.to_dict("records"):
        home_id = int(row["home_team_id"])
        away_id = int(row["away_team_id"])
        home_record = records.setdefault(home_id, [0, 0])
        away_record = records.setdefault(away_id, [0, 0])
        enriched = row.copy()
        enriched["home_wins_prior"] = home_record[0]
        enriched["home_losses_prior"] = home_record[1]
        enriched["away_wins_prior"] = away_record[0]
        enriched["away_losses_prior"] = away_record[1]
        enriched["home_games_prior"] = home_record[0] + home_record[1]
        enriched["away_games_prior"] = away_record[0] + away_record[1]
        enriched["home_season_win_pct_prior"] = win_pct(home_record)
        enriched["away_season_win_pct_prior"] = win_pct(away_record)
        out_rows.append(enriched)

        home_won = bool(row["target_home_win"])
        home_record[0] += int(home_won)
        home_record[1] += int(not home_won)
        away_record[0] += int(not home_won)
        away_record[1] += int(home_won)
    return pd.DataFrame(out_rows)


def score_games(games: pd.DataFrame, weights: SignalWeights) -> pd.DataFrame:
    df = games.copy()
    df["signal_score"] = (
        weights.record * df["record_advantage"]
        + weights.starter * df["starter_xfip_proxy_advantage"]
        + weights.bullpen * df["bullpen_availability_advantage"]
        + weights.lineup * df["lineup_wrc_proxy_advantage"]
    )
    df["pick_home"] = df["signal_score"].ge(0.0)
    df["predicted_winner"] = np.where(df["pick_home"], df["home_team"], df["away_team"])
    df["correct"] = df["pick_home"].eq(df["actual_home_win"])
    return df


def baseline_report(games: pd.DataFrame) -> pd.DataFrame:
    baselines = {
        "better_record": games["season_win_pct_diff"].ge(0.0),
        "lower_starter_xfip_proxy": games["starter_fip_advantage"].ge(0.0),
        "fresher_bullpen": games["bullpen_fatigue_advantage"].ge(0.0),
        "better_lineup_wrc_proxy": games["lineup_offense_advantage"].ge(0.0),
        "home_team": pd.Series(True, index=games.index),
    }
    rows = []
    for name, pick_home in baselines.items():
        scored = games.copy()
        scored["pick_home"] = pick_home.astype(bool)
        scored["correct"] = scored["pick_home"].eq(scored["actual_home_win"])
        rows.append(
            {
                "baseline": name,
                "bets": int(len(scored)),
                "wins": int(scored["correct"].sum()),
                "losses": int((~scored["correct"]).sum()),
                "accuracy": float(scored["correct"].mean()),
            }
        )
        for bucket, group in scored.groupby("record_gap_bucket", dropna=False):
            rows.append(
                {
                    "baseline": f"{name}:{bucket}",
                    "bets": int(len(group)),
                    "wins": int(group["correct"].sum()),
                    "losses": int((~group["correct"]).sum()),
                    "accuracy": float(group["correct"].mean()),
                }
            )
    return pd.DataFrame(rows)


def summarize(scored: pd.DataFrame, label: str, weights: SignalWeights, bucket: str | None = None) -> dict[str, object]:
    wins = int(scored["correct"].sum())
    losses = int((~scored["correct"]).sum())
    return {
        "weight_combo": label,
        "record_weight": weights.record,
        "starter_weight": weights.starter,
        "bullpen_weight": weights.bullpen,
        "lineup_weight": weights.lineup,
        "record_gap_bucket": bucket or "all",
        "bets": int(len(scored)),
        "wins": wins,
        "losses": losses,
        "accuracy": float(wins / len(scored)) if len(scored) else 0.0,
    }


def weight_grid() -> list[SignalWeights]:
    record_weights = [0.25, 0.40, 0.55, 0.70]
    starter_weights = [0.20, 0.35, 0.50, 0.65]
    bullpen_weights = [0.00, 0.10, 0.20]
    lineup_weights = [0.00, 0.10, 0.20]
    combos = []
    for record in record_weights:
        for starter in starter_weights:
            for bullpen in bullpen_weights:
                for lineup in lineup_weights:
                    total = record + starter + bullpen + lineup
                    combos.append(
                        SignalWeights(
                            record=record / total,
                            starter=starter / total,
                            bullpen=bullpen / total,
                            lineup=lineup / total,
                        )
                    )
    # Stable de-dupe after normalization.
    unique = {}
    for combo in combos:
        unique[combo.label] = combo
    return list(unique.values())


def record_gap_bucket(gap: float) -> str:
    if gap < 1.0:
        return "0"
    if gap < 4.0:
        return "1-3"
    if gap < 9.0:
        return "4-8"
    return "9+"


def signed_clip(values: pd.Series | float, scale: float) -> pd.Series:
    series = values if isinstance(values, pd.Series) else pd.Series(values)
    return (series.fillna(0.0).astype(float) / scale).clip(-1.0, 1.0)


def win_pct(record: list[int]) -> float:
    games = record[0] + record[1]
    return record[0] / games if games else 0.5
