from __future__ import annotations

import re
from difflib import get_close_matches


TEAM_ALIASES = {
    "arizona diamondbacks": "Arizona Diamondbacks",
    "ari": "Arizona Diamondbacks",
    "diamondbacks": "Arizona Diamondbacks",
    "atlanta braves": "Atlanta Braves",
    "atl": "Atlanta Braves",
    "braves": "Atlanta Braves",
    "baltimore orioles": "Baltimore Orioles",
    "bal": "Baltimore Orioles",
    "orioles": "Baltimore Orioles",
    "boston red sox": "Boston Red Sox",
    "bos": "Boston Red Sox",
    "red sox": "Boston Red Sox",
    "chicago white sox": "Chicago White Sox",
    "chw": "Chicago White Sox",
    "cws": "Chicago White Sox",
    "white sox": "Chicago White Sox",
    "chicago cubs": "Chicago Cubs",
    "chc": "Chicago Cubs",
    "cubs": "Chicago Cubs",
    "cincinnati reds": "Cincinnati Reds",
    "cin": "Cincinnati Reds",
    "reds": "Cincinnati Reds",
    "cleveland guardians": "Cleveland Guardians",
    "cle": "Cleveland Guardians",
    "guardians": "Cleveland Guardians",
    "colorado rockies": "Colorado Rockies",
    "col": "Colorado Rockies",
    "rockies": "Colorado Rockies",
    "detroit tigers": "Detroit Tigers",
    "det": "Detroit Tigers",
    "tigers": "Detroit Tigers",
    "houston astros": "Houston Astros",
    "hou": "Houston Astros",
    "astros": "Houston Astros",
    "kansas city royals": "Kansas City Royals",
    "kc": "Kansas City Royals",
    "kcr": "Kansas City Royals",
    "royals": "Kansas City Royals",
    "los angeles angels": "Los Angeles Angels",
    "la angels": "Los Angeles Angels",
    "laa": "Los Angeles Angels",
    "angels": "Los Angeles Angels",
    "los angeles dodgers": "Los Angeles Dodgers",
    "la dodgers": "Los Angeles Dodgers",
    "lad": "Los Angeles Dodgers",
    "dodgers": "Los Angeles Dodgers",
    "miami marlins": "Miami Marlins",
    "mia": "Miami Marlins",
    "marlins": "Miami Marlins",
    "milwaukee brewers": "Milwaukee Brewers",
    "mil": "Milwaukee Brewers",
    "brewers": "Milwaukee Brewers",
    "minnesota twins": "Minnesota Twins",
    "min": "Minnesota Twins",
    "twins": "Minnesota Twins",
    "new york yankees": "New York Yankees",
    "ny yankees": "New York Yankees",
    "nyy": "New York Yankees",
    "yankees": "New York Yankees",
    "new york mets": "New York Mets",
    "ny mets": "New York Mets",
    "nym": "New York Mets",
    "mets": "New York Mets",
    "oakland athletics": "Athletics",
    "oak": "Athletics",
    "ath": "Athletics",
    "athletics": "Athletics",
    "a's": "Athletics",
    "philadelphia phillies": "Philadelphia Phillies",
    "phi": "Philadelphia Phillies",
    "phillies": "Philadelphia Phillies",
    "pittsburgh pirates": "Pittsburgh Pirates",
    "pit": "Pittsburgh Pirates",
    "pirates": "Pittsburgh Pirates",
    "san diego padres": "San Diego Padres",
    "sd": "San Diego Padres",
    "sdp": "San Diego Padres",
    "padres": "San Diego Padres",
    "san francisco giants": "San Francisco Giants",
    "sf": "San Francisco Giants",
    "sfg": "San Francisco Giants",
    "giants": "San Francisco Giants",
    "seattle mariners": "Seattle Mariners",
    "sea": "Seattle Mariners",
    "mariners": "Seattle Mariners",
    "st. louis cardinals": "St. Louis Cardinals",
    "st louis cardinals": "St. Louis Cardinals",
    "stl": "St. Louis Cardinals",
    "cardinals": "St. Louis Cardinals",
    "tampa bay rays": "Tampa Bay Rays",
    "tb": "Tampa Bay Rays",
    "tbr": "Tampa Bay Rays",
    "rays": "Tampa Bay Rays",
    "texas rangers": "Texas Rangers",
    "tex": "Texas Rangers",
    "rangers": "Texas Rangers",
    "toronto blue jays": "Toronto Blue Jays",
    "tor": "Toronto Blue Jays",
    "blue jays": "Toronto Blue Jays",
    "washington nationals": "Washington Nationals",
    "wsh": "Washington Nationals",
    "was": "Washington Nationals",
    "nationals": "Washington Nationals",
}


def normalize_team_name(name: str | None) -> str | None:
    if not name:
        return None
    key = re.sub(r"\s+", " ", name.lower().replace(".", "")).strip()
    if key in TEAM_ALIASES:
        return TEAM_ALIASES[key]
    choices = list(TEAM_ALIASES)
    match = get_close_matches(key, choices, n=1, cutoff=0.86)
    return TEAM_ALIASES[match[0]] if match else name
