from datetime import date, datetime
from typing import Protocol
from uuid import UUID

from app.schemas.domain import Play
from app.schemas.nba_data import (
    NBAGame,
    NBAPlayer,
    NBATeam,
    PlayerGameStats,
    PreferredLineupCandidate,
)
from app.schemas.possessions import PossessionReconstruction, RealPossession


class PlayRepository(Protocol):
    def save(self, play: Play) -> Play: ...

    def get(self, play_id: UUID) -> Play | None: ...

    def list(self) -> list[Play]: ...

    def delete(self, play_id: UUID) -> bool: ...


class NBADataRepository(Protocol):
    def initialize(self) -> None: ...
    def save_teams(self, teams: list[NBATeam]) -> None: ...
    def list_teams(self) -> list[NBATeam]: ...
    def get_team(self, team_id: UUID) -> NBATeam | None: ...
    def save_players(self, players: list[NBAPlayer]) -> None: ...
    def replace_roster(self, team_id: UUID, season: str, players: list[NBAPlayer]) -> None: ...
    def list_roster(self, team_id: UUID, season: str) -> list[NBAPlayer]: ...
    def roster_retrieved_at(self, team_id: UUID, season: str) -> datetime | None: ...
    def replace_preferred_lineup(
        self,
        team_id: UUID,
        season: str,
        candidates: list[PreferredLineupCandidate],
    ) -> None: ...
    def list_preferred_lineup(
        self, team_id: UUID, season: str
    ) -> list[PreferredLineupCandidate]: ...
    def preferred_lineup_retrieved_at(self, team_id: UUID, season: str) -> datetime | None: ...
    def save_games(self, games: list[NBAGame]) -> None: ...
    def list_games(
        self,
        *,
        game_date: date | None = None,
        season: str | None = None,
        team_id: UUID | None = None,
    ) -> list[NBAGame]: ...
    def get_game(self, game_id: UUID) -> NBAGame | None: ...
    def save_player_game_stats(self, stats: list[PlayerGameStats]) -> None: ...
    def list_player_game_stats(self, game_id: UUID) -> list[PlayerGameStats]: ...


class PossessionRepository(Protocol):
    def save_possessions(self, possessions: list[RealPossession]) -> None: ...
    def list_possessions(self, game_id: UUID) -> list[RealPossession]: ...
    def get_possession(self, possession_id: UUID) -> RealPossession | None: ...
    def save_reconstruction(
        self, reconstruction: PossessionReconstruction
    ) -> PossessionReconstruction: ...
    def list_reconstructions(self, possession_id: UUID) -> list[PossessionReconstruction]: ...
